version: "3.8"

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    # Real backend service

  frontend:
    build: ./frontend/innosync
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      NODE_ENV: production
    restart: unless-stopped

  ml:
    build: ./ML
    ports:
      - "8000:8000"
    depends_on:
      - app
    environment:
      - BACKEND_URL=http://app:8080
    env_file:
      - ML/.env
    restart: unless-stopped

  # mock-backend:
  #   build: ./ML
  #   command: ["python", "mock_backend.py"]
  #   ports:
  #     - "8081:8080"
  #   restart: unless-stopped
    # Mock backend for ML API testing

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: registration
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "registration"]
      interval: 5s
      retries: 5
