server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/registration
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#springdoc:
#  swagger-ui:
#    enabled: false