server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#springdoc:
#  swagger-ui:
#    enabled: false